name: WakeyWakey
options:
  bundleIdPrefix: com.wakeywakey
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  WakeyWakey:
    type: application
    platform: iOS
    sources:
      - path: Sources
        type: group
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.wakeywakey.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ENABLE_PREVIEWS: "YES"
    info:
      path: Sources/Resources/Info.plist
      properties:
        CFBundleName: WakeyWakey
        CFBundleDisplayName: WakeyWakey
        CFBundleIdentifier: com.wakeywakey.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: WakeyWakey
        UILaunchScreen:
          UIColorName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        NSUserActivityTypes: []
